[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql", "nodejs", "pnpm"]

[phases.install]
cmds = ["cd /app && pnpm install"]

[phases.build]
cmds = ["cd /app && pnpm build", "cp -r /app/dist/* /app/"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
