[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm config set store-dir /app/.pnpm-store", "cd /app && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd /app && pnpm install", "cd /app && pnpm build"]

[start]
cmd = "sh start.sh"
